# Generated by Django 3.2.3 on 2021-10-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
