# Generated by Django 3.2.3 on 2021-10-26 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0002_postlike_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='like_count',
        ),
        migrations.AddField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comment',
        ),
    ]
