# Generated by Django 3.2.3 on 2021-10-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('use', '0003_auto_20211026_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentslike',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='commentslike',
            name='like_count',
        ),
        migrations.AddField(
            model_name='commentslike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentslike',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
