# Generated by Django 3.2.3 on 2021-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailauthentication',
            name='security_code',
            field=models.IntegerField(verbose_name='보안코드'),
        ),
    ]
